[project]
name = "modbux-proxy-debugger"
version = "0.1.0"
description = "modbus tcp debugger tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "pyyaml>=6.0.3",
]
